# Generated by Django 3.1.4 on 2021-01-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
